In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)

In [3]:
a

array([-0.33724735, -0.17237964,  0.49383586, -1.54044057,  2.6262971 ])

In [4]:
a = np.random.randn(5,1)
a

array([[ 0.26703933],
       [-1.71705461],
       [ 1.04620189],
       [ 1.25792661],
       [ 0.01138182]])

In [5]:
a.T

array([[ 0.26703933, -1.71705461,  1.04620189,  1.25792661,  0.01138182]])

In [7]:
b = np.dot(a, a.T)

In [9]:
b.shape

(5L, 5L)

In [10]:
b

array([[  7.13100057e-02,  -4.58521119e-01,   2.79377056e-01,
          3.35915885e-01,   3.03939463e-03],
       [ -4.58521119e-01,   2.94827654e+00,  -1.79638578e+00,
         -2.15992869e+00,  -1.95432129e-02],
       [  2.79377056e-01,  -1.79638578e+00,   1.09453840e+00,
          1.31604520e+00,   1.19076855e-02],
       [  3.35915885e-01,  -2.15992869e+00,   1.31604520e+00,
          1.58237937e+00,   1.43174990e-02],
       [  3.03939463e-03,  -1.95432129e-02,   1.19076855e-02,
          1.43174990e-02,   1.29545912e-04]])

In [14]:
assert(a.shape==(5,1))

In [15]:
bad_a = np.random.randn(5)

In [16]:
bad_a.shape

(5L,)

In [19]:
bad_a.reshape((5,1))

array([[-0.24301355],
       [ 0.58817709],
       [-2.59539573],
       [-0.93680932],
       [-1.22411879]])

In [20]:
bad_a

array([-0.24301355,  0.58817709, -2.59539573, -0.93680932, -1.22411879])

In [21]:
type(bad_a)

numpy.ndarray

In [22]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
c

array([[ 1.289923  ,  2.26993376,  0.95244089],
       [ 1.75527634,  2.64059045,  3.50632358]])

In [23]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
c

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [24]:
np.dot(a, b)

array([[ 0.33438853, -1.31335154],
       [ 2.1167765 , -0.91568555],
       [-0.43491309, -0.45926016],
       [ 0.73820908, -1.83252472]])

In [25]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(4, 3) # b.shape = (4, 3)
c = a*b
c

array([[  7.49314065e-01,   9.06559094e-01,   5.07388750e-01],
       [ -6.08814516e-01,  -6.22182850e-01,  -1.52780146e+00],
       [  4.77776214e-03,   1.14511890e-01,  -2.59849541e-01],
       [ -5.03990318e-04,   9.70089928e-02,   3.41726118e-01]])

In [26]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c

array([[ 0.60445725,  0.36589343, -0.03411841],
       [ 0.10847596, -0.09372256, -0.67236136],
       [ 3.11550095, -3.85011511, -1.20592786]])

In [27]:
a

array([[-1.60109657, -0.96918469,  0.09037341],
       [-0.15741346,  0.13600426,  0.97568835],
       [-1.15461156,  1.42686119,  0.44691954]])

In [28]:
b

array([[-0.37752704],
       [-0.68911488],
       [-2.6983109 ]])

In [29]:
np.exp?

In [30]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

In [31]:
image.shape

(3L, 3L, 2L)

In [38]:
c_norm = np.linalg.norm(c, axis=1, keepdims=True)
c_norm

array([[ 0.70739709],
       [ 0.68747419],
       [ 5.0974498 ]])

In [37]:
c

array([[ 0.60445725,  0.36589343, -0.03411841],
       [ 0.10847596, -0.09372256, -0.67236136],
       [ 3.11550095, -3.85011511, -1.20592786]])

In [39]:
c / c_norm

array([[ 0.85448083,  0.5172391 , -0.04823091],
       [ 0.15778914, -0.13632884, -0.97801689],
       [ 0.61118816, -0.75530221, -0.23657474]])

In [44]:
c.reshape((c.shape[0]*c.shape[1], 1))

array([[ 0.60445725],
       [ 0.36589343],
       [-0.03411841],
       [ 0.10847596],
       [-0.09372256],
       [-0.67236136],
       [ 3.11550095],
       [-3.85011511],
       [-1.20592786]])

In [46]:
np.zeros((4, 1))

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [47]:
a

array([[-1.60109657, -0.96918469,  0.09037341],
       [-0.15741346,  0.13600426,  0.97568835],
       [-1.15461156,  1.42686119,  0.44691954]])

In [48]:
a.T

array([[-1.60109657, -0.15741346, -1.15461156],
       [-0.96918469,  0.13600426,  1.42686119],
       [ 0.09037341,  0.97568835,  0.44691954]])

In [53]:
np.sum(b, axis=0)

array([-3.76495282])

In [52]:
b

array([[-0.37752704],
       [-0.68911488],
       [-2.6983109 ]])

In [54]:
np.where(a < 0, -1, 0)

array([[-1, -1,  0],
       [-1,  0,  0],
       [-1,  0,  0]])